name: CI

on:
  push:
jobs:
  go-build:
    runs-on: ubuntu-latest
    container: golang:1.18beta2-buster
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
      - name: test
        run: make test